### ISSUE TITLE
PHP Fatal error: Uncaught UnexpectedValueException: DirectoryIterator::__construct(...)

### ISSUE THREAD

**Issue by GaryJones** [edsonmedina/php_testability#80]
Running php_testability against the Genesis Framework (parent theme for WordPress), and it fails. Digging down to the reported first failure, and the following against [this](https://gist.github.com/GaryJones/79c27030c0918ada881094e3614c2387) gives:

```
./vendor/bin/testability ./lib/admin/menu.php -x vendor -vvv
```

```
PHP_Testability by Edson Medina
Analysing code on "/Users/gary/code/themes/genesis/lib/admin/menu.php"...
PHP Fatal error:  Uncaught UnexpectedValueException: DirectoryIterator::__construct(/Users/gary/code/themes/genesis/lib/admin/menu.php): failed to open dir: Not a directory in /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/FileIterator.php:42
Stack trace:
#0 /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/FileIterator.php(42): DirectoryIterator->__construct('/Users/gary/cod...')
#1 /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/Testability.php(58): edsonmedina\php_testability\FileIterator->iterate(Object(edsonmedina\php_testability\Contexts\RootContext))
#2 /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/testability(55): edsonmedina\php_testability\Testability->runReport()
#3 {main}
  thrown in /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/FileIterator.php on line 42

Fatal error: Uncaught UnexpectedValueException: DirectoryIterator::__construct(/Users/gary/code/themes/genesis/lib/admin/menu.php): failed to open dir: Not a directory in /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/FileIterator.php:42
Stack trace:
#0 /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/FileIterator.php(42): DirectoryIterator->__construct('/Users/gary/cod...')
#1 /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/Testability.php(58): edsonmedina\php_testability\FileIterator->iterate(Object(edsonmedina\php_testability\Contexts\RootContext))
#2 /Users/gary/code/themes/genesis/vendor/edsonmedina/php_testability/src/testability(55): edsonmedina\php_testability\Testability->runReport()
#3 {main}
```

Other files in the same directory seem to pass fine - I'm not sure why this file seems to be being treated as a directory.

**Comment by edsonmedina** [comment]
Should work now, can you try?

**Comment by GaryJones** [comment]
Running:
```
./vendor/bin/testability ./lib/admin/menu.php -x vendor -vvv
```

Gives the same error, but running:

```
./vendor/bin/testability . -x vendor -vvv
```

and the troublesome menu.php goes through OK.

**Comment by edsonmedina** [comment]
Fixed in #79.

**Comment by GaryJones** [comment]
Thanks.

No fatal errors are thrown now, but I am getting a lot of repeated PHP Notices when running the single file or whole directory as before:

![screenshot 2017-07-13 13 57 30](https://user-images.githubusercontent.com/88371/28167420-88ba5d18-67d3-11e7-9575-1e708b2bc651.png)

**Comment by edsonmedina** [comment]
Fixed.
Thank you for your patience.

**Comment by GaryJones** [comment]
Confirming the fix for this file, though another couple of Notices remain related to another file - opened in #81.
